### ISSUE TITLE
Custom assertions not shown on doc site?

### ISSUE THREAD

**Issue by papandreou** [unexpectedjs/unexpected-check#1]
I took a look at the front page of the doc site and found it a bit confusing that the custom assertions defined in the bootstrapping code (https://github.com/unexpectedjs/unexpected-check/blob/master/bootstrap.js#L6-L24) were not declared, but being used in snippets like this one:

```js
  expect(sorted, 'to have length', arr.length)
    .and('first item to be less than or equal to all', arr)
    .and('last item to be greater than or equal to all', arr);
```

Since they're only being used on the front page, it might make sense to move them there?

**Comment by sunesimonsen** [comment]
I rewrote the example on the front page to not use the assertions.
